name: Deploy Site
on:
  push:
    branches:
      - main

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages    
# permissions:
#   contents: read
#   pages: write
#   id-token: write

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: statiq-dopetrope-demo
    steps:
      - name: Get Source
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Install .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'
      - run: dotnet run -- deploy -l "Trace"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
